// GENERATED by tools/generate-map.mjs (seed 20260924). Do not edit by hand;
// change the generator and re-run `pnpm map:generate`.
// Stats: {"sites":36,"routes":44,"regions":24,"capacity":29,"mis":19,"sameResourceNeighbours":3,"kingsHighwayDistance":6,"minRegionsPerSite":2}
import type { MapDefinition } from "../types.js";

export const GREENVALE_MAP: MapDefinition = {
  "id": "greenvale",
  "name": "The Greenvale",
  "width": 1600,
  "height": 1000,
  "coastline": "M1500,500L1497.3,537.5L1489.4,574.7L1476.1,611.3L1457.8,647.1L1434.4,681.7L1406.2,715L1373.4,746.6L1336.2,776.4L1295,804.1L1250,829.4L1201.5,852.2L1150,872.4L1095.8,889.7L1039.4,904.1L981.2,915.3L921.6,923.5L861,928.4L800,930L739,928.4L678.4,923.5L618.8,915.3L560.6,904.1L504.2,889.7L450,872.4L398.5,852.2L350,829.4L305,804.1L263.8,776.4L226.6,746.6L193.8,715L165.6,681.7L142.2,647.1L123.9,611.3L110.6,574.7L102.7,537.5L100,500L102.7,462.5L110.6,425.3L123.9,388.7L142.2,352.9L165.6,318.3L193.8,285L226.6,253.4L263.8,223.6L305,195.9L350,170.6L398.5,147.8L450,127.6L504.2,110.3L560.6,95.9L618.8,84.7L678.4,76.5L739,71.6L800,70L861,71.6L921.6,76.5L981.2,84.7L1039.4,95.9L1095.8,110.3L1150,127.6L1201.5,147.8L1250,170.6L1295,195.9L1336.2,223.6L1373.4,253.4L1406.2,285L1434.4,318.3L1457.8,352.9L1476.1,388.7L1489.4,425.3L1497.3,462.5Z",
  "sites": [
    {
      "id": "site_01",
      "x": 980.1,
      "y": 84.5,
      "adjacentRegionIds": [
        "region_01",
        "region_03"
      ],
      "tradePost": {
        "resource": "stone",
        "give": 2
      }
    },
    {
      "id": "site_02",
      "x": 778.9,
      "y": 241.1,
      "adjacentRegionIds": [
        "region_01",
        "region_02",
        "region_08"
      ],
      "landmarkId": "sacred_grove"
    },
    {
      "id": "site_03",
      "x": 935.6,
      "y": 247.9,
      "adjacentRegionIds": [
        "region_01",
        "region_03",
        "region_07"
      ]
    },
    {
      "id": "site_04",
      "x": 586.6,
      "y": 255.6,
      "adjacentRegionIds": [
        "region_02",
        "region_04",
        "region_10"
      ]
    },
    {
      "id": "site_05",
      "x": 859.7,
      "y": 277.3,
      "adjacentRegionIds": [
        "region_01",
        "region_07",
        "region_08"
      ]
    },
    {
      "id": "site_06",
      "x": 686.4,
      "y": 289.3,
      "adjacentRegionIds": [
        "region_02",
        "region_08",
        "region_10"
      ]
    },
    {
      "id": "site_07",
      "x": 1065,
      "y": 324.9,
      "adjacentRegionIds": [
        "region_03",
        "region_05",
        "region_07"
      ]
    },
    {
      "id": "site_08",
      "x": 475.1,
      "y": 364.2,
      "adjacentRegionIds": [
        "region_04",
        "region_10",
        "region_11"
      ]
    },
    {
      "id": "site_09",
      "x": 423.8,
      "y": 367.2,
      "adjacentRegionIds": [
        "region_04",
        "region_09",
        "region_11"
      ],
      "landmarkId": "adventurers_inn"
    },
    {
      "id": "site_10",
      "x": 1467.9,
      "y": 372.7,
      "adjacentRegionIds": [
        "region_06",
        "region_12"
      ]
    },
    {
      "id": "site_11",
      "x": 1086.8,
      "y": 381.7,
      "adjacentRegionIds": [
        "region_05",
        "region_07",
        "region_13"
      ]
    },
    {
      "id": "site_12",
      "x": 1197.6,
      "y": 405,
      "adjacentRegionIds": [
        "region_05",
        "region_06",
        "region_13"
      ]
    },
    {
      "id": "site_13",
      "x": 699.2,
      "y": 448.5,
      "adjacentRegionIds": [
        "region_08",
        "region_10",
        "region_14"
      ]
    },
    {
      "id": "site_14",
      "x": 864,
      "y": 449.5,
      "adjacentRegionIds": [
        "region_07",
        "region_08",
        "region_15"
      ]
    },
    {
      "id": "site_15",
      "x": 1004.9,
      "y": 472.7,
      "adjacentRegionIds": [
        "region_07",
        "region_13",
        "region_15"
      ]
    },
    {
      "id": "site_16",
      "x": 1258.7,
      "y": 473.8,
      "adjacentRegionIds": [
        "region_06",
        "region_12",
        "region_13"
      ],
      "landmarkId": "wizard_tower"
    },
    {
      "id": "site_17",
      "x": 822.6,
      "y": 478,
      "adjacentRegionIds": [
        "region_08",
        "region_14",
        "region_15"
      ],
      "landmarkId": "royal_castle"
    },
    {
      "id": "site_18",
      "x": 333.8,
      "y": 500.5,
      "adjacentRegionIds": [
        "region_09",
        "region_11",
        "region_16",
        "region_17"
      ]
    },
    {
      "id": "site_19",
      "x": 608.7,
      "y": 517.5,
      "adjacentRegionIds": [
        "region_10",
        "region_11",
        "region_14",
        "region_18"
      ]
    },
    {
      "id": "site_20",
      "x": 1262,
      "y": 547.1,
      "adjacentRegionIds": [
        "region_12",
        "region_13",
        "region_19"
      ]
    },
    {
      "id": "site_21",
      "x": 478.4,
      "y": 621.2,
      "adjacentRegionIds": [
        "region_11",
        "region_17",
        "region_18"
      ]
    },
    {
      "id": "site_22",
      "x": 1036.5,
      "y": 628.1,
      "adjacentRegionIds": [
        "region_13",
        "region_15",
        "region_21"
      ]
    },
    {
      "id": "site_23",
      "x": 821,
      "y": 635.6,
      "adjacentRegionIds": [
        "region_14",
        "region_15",
        "region_20"
      ]
    },
    {
      "id": "site_24",
      "x": 1151.1,
      "y": 654.6,
      "adjacentRegionIds": [
        "region_13",
        "region_19",
        "region_21"
      ]
    },
    {
      "id": "site_25",
      "x": 1447.8,
      "y": 661.8,
      "adjacentRegionIds": [
        "region_12",
        "region_19"
      ]
    },
    {
      "id": "site_26",
      "x": 476.2,
      "y": 670.8,
      "adjacentRegionIds": [
        "region_17",
        "region_18",
        "region_22"
      ]
    },
    {
      "id": "site_27",
      "x": 709.2,
      "y": 671.4,
      "adjacentRegionIds": [
        "region_14",
        "region_18",
        "region_20"
      ]
    },
    {
      "id": "site_28",
      "x": 931.5,
      "y": 716,
      "adjacentRegionIds": [
        "region_15",
        "region_20",
        "region_21",
        "region_24"
      ]
    },
    {
      "id": "site_29",
      "x": 678.3,
      "y": 735.2,
      "adjacentRegionIds": [
        "region_18",
        "region_20",
        "region_23"
      ]
    },
    {
      "id": "site_30",
      "x": 216.7,
      "y": 737.1,
      "adjacentRegionIds": [
        "region_16",
        "region_17"
      ]
    },
    {
      "id": "site_31",
      "x": 539.3,
      "y": 755.4,
      "adjacentRegionIds": [
        "region_18",
        "region_22",
        "region_23"
      ],
      "landmarkId": "dwarven_hall"
    },
    {
      "id": "site_32",
      "x": 266,
      "y": 777.9,
      "adjacentRegionIds": [
        "region_17",
        "region_22"
      ]
    },
    {
      "id": "site_33",
      "x": 1219.2,
      "y": 843.9,
      "adjacentRegionIds": [
        "region_19",
        "region_21"
      ],
      "tradePost": {
        "resource": "iron",
        "give": 2
      }
    },
    {
      "id": "site_34",
      "x": 751.1,
      "y": 880.7,
      "adjacentRegionIds": [
        "region_20",
        "region_23",
        "region_24"
      ]
    },
    {
      "id": "site_35",
      "x": 502.9,
      "y": 889.3,
      "adjacentRegionIds": [
        "region_22",
        "region_23"
      ]
    },
    {
      "id": "site_36",
      "x": 1025.9,
      "y": 906.7,
      "adjacentRegionIds": [
        "region_21",
        "region_24"
      ]
    }
  ],
  "routes": [
    {
      "id": "route_01",
      "siteA": "site_02",
      "siteB": "site_05",
      "kind": "road"
    },
    {
      "id": "route_02",
      "siteA": "site_02",
      "siteB": "site_06",
      "kind": "trail"
    },
    {
      "id": "route_03",
      "siteA": "site_03",
      "siteB": "site_01",
      "kind": "road"
    },
    {
      "id": "route_04",
      "siteA": "site_04",
      "siteB": "site_08",
      "kind": "road"
    },
    {
      "id": "route_05",
      "siteA": "site_05",
      "siteB": "site_03",
      "kind": "road"
    },
    {
      "id": "route_06",
      "siteA": "site_05",
      "siteB": "site_14",
      "kind": "road"
    },
    {
      "id": "route_07",
      "siteA": "site_06",
      "siteB": "site_04",
      "kind": "trail"
    },
    {
      "id": "route_08",
      "siteA": "site_06",
      "siteB": "site_13",
      "kind": "trail"
    },
    {
      "id": "route_09",
      "siteA": "site_07",
      "siteB": "site_03",
      "kind": "road"
    },
    {
      "id": "route_10",
      "siteA": "site_09",
      "siteB": "site_08",
      "kind": "road"
    },
    {
      "id": "route_11",
      "siteA": "site_09",
      "siteB": "site_18",
      "kind": "trail"
    },
    {
      "id": "route_12",
      "siteA": "site_11",
      "siteB": "site_07",
      "kind": "road"
    },
    {
      "id": "route_13",
      "siteA": "site_11",
      "siteB": "site_15",
      "kind": "pass"
    },
    {
      "id": "route_14",
      "siteA": "site_12",
      "siteB": "site_11",
      "kind": "road"
    },
    {
      "id": "route_15",
      "siteA": "site_12",
      "siteB": "site_16",
      "kind": "road"
    },
    {
      "id": "route_16",
      "siteA": "site_13",
      "siteB": "site_17",
      "kind": "road"
    },
    {
      "id": "route_17",
      "siteA": "site_15",
      "siteB": "site_14",
      "kind": "bridge"
    },
    {
      "id": "route_18",
      "siteA": "site_15",
      "siteB": "site_22",
      "kind": "road"
    },
    {
      "id": "route_19",
      "siteA": "site_16",
      "siteB": "site_10",
      "kind": "road"
    },
    {
      "id": "route_20",
      "siteA": "site_17",
      "siteB": "site_14",
      "kind": "road"
    },
    {
      "id": "route_21",
      "siteA": "site_17",
      "siteB": "site_23",
      "kind": "pass"
    },
    {
      "id": "route_22",
      "siteA": "site_18",
      "siteB": "site_21",
      "kind": "road"
    },
    {
      "id": "route_23",
      "siteA": "site_18",
      "siteB": "site_30",
      "kind": "bridge"
    },
    {
      "id": "route_24",
      "siteA": "site_19",
      "siteB": "site_08",
      "kind": "trail"
    },
    {
      "id": "route_25",
      "siteA": "site_19",
      "siteB": "site_13",
      "kind": "road"
    },
    {
      "id": "route_26",
      "siteA": "site_19",
      "siteB": "site_21",
      "kind": "trail"
    },
    {
      "id": "route_27",
      "siteA": "site_20",
      "siteB": "site_16",
      "kind": "bridge"
    },
    {
      "id": "route_28",
      "siteA": "site_20",
      "siteB": "site_24",
      "kind": "trail"
    },
    {
      "id": "route_29",
      "siteA": "site_22",
      "siteB": "site_28",
      "kind": "road"
    },
    {
      "id": "route_30",
      "siteA": "site_23",
      "siteB": "site_28",
      "kind": "road"
    },
    {
      "id": "route_31",
      "siteA": "site_24",
      "siteB": "site_22",
      "kind": "road"
    },
    {
      "id": "route_32",
      "siteA": "site_24",
      "siteB": "site_33",
      "kind": "trail"
    },
    {
      "id": "route_33",
      "siteA": "site_25",
      "siteB": "site_20",
      "kind": "road"
    },
    {
      "id": "route_34",
      "siteA": "site_26",
      "siteB": "site_21",
      "kind": "trail"
    },
    {
      "id": "route_35",
      "siteA": "site_26",
      "siteB": "site_32",
      "kind": "road"
    },
    {
      "id": "route_36",
      "siteA": "site_27",
      "siteB": "site_19",
      "kind": "road"
    },
    {
      "id": "route_37",
      "siteA": "site_27",
      "siteB": "site_23",
      "kind": "trail"
    },
    {
      "id": "route_38",
      "siteA": "site_27",
      "siteB": "site_29",
      "kind": "road"
    },
    {
      "id": "route_39",
      "siteA": "site_29",
      "siteB": "site_34",
      "kind": "road"
    },
    {
      "id": "route_40",
      "siteA": "site_31",
      "siteB": "site_26",
      "kind": "road"
    },
    {
      "id": "route_41",
      "siteA": "site_31",
      "siteB": "site_29",
      "kind": "road"
    },
    {
      "id": "route_42",
      "siteA": "site_34",
      "siteB": "site_28",
      "kind": "pass"
    },
    {
      "id": "route_43",
      "siteA": "site_35",
      "siteB": "site_31",
      "kind": "pass"
    },
    {
      "id": "route_44",
      "siteA": "site_36",
      "siteB": "site_28",
      "kind": "trail"
    }
  ],
  "regions": [
    {
      "id": "region_01",
      "name": "Moonglade",
      "resource": "essence",
      "capacity": 1,
      "path": "M778.9,241.1L766.3,70.9L800,70L861,71.6L921.6,76.5L980.1,84.5L935.6,247.9L859.7,277.3Z",
      "labelX": 864.9,
      "labelY": 162.4,
      "adjacentSiteIds": [
        "site_01",
        "site_02",
        "site_03",
        "site_05"
      ]
    },
    {
      "id": "region_02",
      "name": "Greystone Quarry",
      "resource": "stone",
      "capacity": 1,
      "path": "M544.1,100.1L560.6,95.9L618.8,84.7L678.4,76.5L739,71.6L766.3,70.9L778.9,241.1L686.4,289.3L586.6,255.6Z",
      "labelX": 670.9,
      "labelY": 172.7,
      "adjacentSiteIds": [
        "site_02",
        "site_04",
        "site_06"
      ]
    },
    {
      "id": "region_03",
      "name": "Goldenfurrow Fields",
      "resource": "grain",
      "capacity": 1,
      "path": "M980.1,84.5L981.2,84.7L1039.4,95.9L1095.8,110.3L1150,127.6L1159.1,131.2L1065,324.9L935.6,247.9Z",
      "labelX": 1039.8,
      "labelY": 193.8,
      "adjacentSiteIds": [
        "site_01",
        "site_03",
        "site_07"
      ]
    },
    {
      "id": "region_04",
      "name": "Millbrook Meadows",
      "resource": "grain",
      "capacity": 1,
      "path": "M301.8,198.1L305,195.9L350,170.6L398.5,147.8L450,127.6L504.2,110.3L544.1,100.1L586.6,255.6L475.1,364.2L423.8,367.2Z",
      "labelX": 458.3,
      "labelY": 231.2,
      "adjacentSiteIds": [
        "site_04",
        "site_08",
        "site_09"
      ]
    },
    {
      "id": "region_05",
      "name": "Hayward Farms",
      "resource": "grain",
      "capacity": 2,
      "path": "M1159.1,131.2L1201.5,147.8L1250,170.6L1295,195.9L1302.9,201.2L1197.6,405L1086.8,381.7L1065,324.9Z",
      "labelX": 1177.8,
      "labelY": 272.2,
      "adjacentSiteIds": [
        "site_07",
        "site_11",
        "site_12"
      ]
    },
    {
      "id": "region_06",
      "name": "Cragmoor Hills",
      "resource": "stone",
      "capacity": 1,
      "path": "M1197.6,405L1302.9,201.2L1336.2,223.6L1373.4,253.4L1406.2,285L1434.4,318.3L1457.8,352.9L1467.9,372.7L1258.7,473.8Z",
      "labelX": 1323.5,
      "labelY": 347.7,
      "adjacentSiteIds": [
        "site_10",
        "site_12",
        "site_16"
      ]
    },
    {
      "id": "region_07",
      "name": "Flintridge",
      "resource": "stone",
      "capacity": 1,
      "path": "M859.7,277.3L935.6,247.9L1065,324.9L1086.8,381.7L1004.9,472.7L864,449.5Z",
      "labelX": 958.4,
      "labelY": 365.2,
      "adjacentSiteIds": [
        "site_03",
        "site_05",
        "site_07",
        "site_11",
        "site_14",
        "site_15"
      ]
    },
    {
      "id": "region_08",
      "name": "Oakenshaw Wood",
      "resource": "timber",
      "capacity": 2,
      "path": "M686.4,289.3L778.9,241.1L859.7,277.3L864,449.5L822.6,478L699.2,448.5Z",
      "labelX": 779.2,
      "labelY": 361.6,
      "adjacentSiteIds": [
        "site_02",
        "site_05",
        "site_06",
        "site_13",
        "site_14",
        "site_17"
      ]
    },
    {
      "id": "region_09",
      "name": "Slatefell Scarp",
      "resource": "stone",
      "capacity": 1,
      "path": "M113.3,418L123.9,388.7L142.2,352.9L165.6,318.3L193.8,285L226.6,253.4L263.8,223.6L301.8,198.1L423.8,367.2L334.9,500.2L332.7,500.8Z",
      "labelX": 275.7,
      "labelY": 361.1,
      "adjacentSiteIds": [
        "site_09",
        "site_18"
      ]
    },
    {
      "id": "region_10",
      "name": "Deepdelve Mine",
      "resource": "iron",
      "capacity": 1,
      "path": "M475.1,364.2L586.6,255.6L686.4,289.3L699.2,448.5L611.3,507Z",
      "labelX": 605,
      "labelY": 375.2,
      "adjacentSiteIds": [
        "site_04",
        "site_06",
        "site_08",
        "site_13",
        "site_19"
      ]
    },
    {
      "id": "region_11",
      "name": "Faerie Ring",
      "resource": "essence",
      "capacity": 1,
      "path": "M334.9,500.2L423.8,367.2L475.1,364.2L611.3,507L606.1,528L478.4,621.2Z",
      "labelX": 471.6,
      "labelY": 490.8,
      "adjacentSiteIds": [
        "site_08",
        "site_09",
        "site_18",
        "site_19",
        "site_21"
      ]
    },
    {
      "id": "region_12",
      "name": "Rustvein Pits",
      "resource": "iron",
      "capacity": 1,
      "path": "M1500,500L1497.3,537.5L1489.4,574.7L1476.1,611.3L1457.8,647.1L1447.8,661.8L1262,547.1L1258.7,473.8L1467.9,372.7L1476.1,388.7L1489.4,425.3L1497.3,462.5Z",
      "labelX": 1396.2,
      "labelY": 514.3,
      "adjacentSiteIds": [
        "site_10",
        "site_16",
        "site_20",
        "site_25"
      ]
    },
    {
      "id": "region_13",
      "name": "Whisperpine Forest",
      "resource": "timber",
      "capacity": 1,
      "path": "M1004.9,472.7L1086.8,381.7L1197.6,405L1258.7,473.8L1262,547.1L1151.1,654.6L1036.5,628.1Z",
      "labelX": 1130.7,
      "labelY": 516.5,
      "adjacentSiteIds": [
        "site_11",
        "site_12",
        "site_15",
        "site_16",
        "site_20",
        "site_22",
        "site_24"
      ]
    },
    {
      "id": "region_14",
      "name": "Anvilhold Mine",
      "resource": "iron",
      "capacity": 1,
      "path": "M709.2,671.4L606.1,528L611.3,507L699.2,448.5L822.6,478L821,635.6Z",
      "labelX": 728.9,
      "labelY": 553.2,
      "adjacentSiteIds": [
        "site_13",
        "site_17",
        "site_19",
        "site_23",
        "site_27"
      ]
    },
    {
      "id": "region_15",
      "name": "Cinderholm Shafts",
      "resource": "iron",
      "capacity": 2,
      "path": "M821,635.6L822.6,478L864,449.5L1004.9,472.7L1036.5,628.1L931.9,707.2Z",
      "labelX": 921.5,
      "labelY": 570.1,
      "adjacentSiteIds": [
        "site_14",
        "site_15",
        "site_17",
        "site_22",
        "site_23",
        "site_28"
      ]
    },
    {
      "id": "region_16",
      "name": "Brackenwold",
      "resource": "timber",
      "capacity": 1,
      "path": "M216.7,737.1L193.8,715L165.6,681.7L142.2,647.1L123.9,611.3L110.6,574.7L102.7,537.5L100,500L102.7,462.5L110.6,425.3L113.3,418L332.7,500.8Z",
      "labelX": 200.2,
      "labelY": 559.6,
      "adjacentSiteIds": [
        "site_18",
        "site_30"
      ]
    },
    {
      "id": "region_17",
      "name": "Barleycombe",
      "resource": "grain",
      "capacity": 1,
      "path": "M266,777.9L263.8,776.4L226.6,746.6L216.7,737.1L332.7,500.8L334.9,500.2L478.4,621.2L476.2,670.8Z",
      "labelX": 346.5,
      "labelY": 649,
      "adjacentSiteIds": [
        "site_18",
        "site_21",
        "site_26",
        "site_30",
        "site_32"
      ]
    },
    {
      "id": "region_18",
      "name": "Elderbough Thicket",
      "resource": "timber",
      "capacity": 1,
      "path": "M606.1,528L709.2,671.4L678.3,735.2L539.3,755.4L476.2,670.8L478.4,621.2Z",
      "labelX": 589.2,
      "labelY": 655.9,
      "adjacentSiteIds": [
        "site_19",
        "site_21",
        "site_26",
        "site_27",
        "site_29",
        "site_31"
      ]
    },
    {
      "id": "region_19",
      "name": "Shimmermere Ruins",
      "resource": "essence",
      "capacity": 2,
      "path": "M1447.8,661.8L1434.4,681.7L1406.2,715L1373.4,746.6L1336.2,776.4L1295,804.1L1250,829.4L1219.2,843.9L1151.1,654.6L1262,547.1Z",
      "labelX": 1283.3,
      "labelY": 689.5,
      "adjacentSiteIds": [
        "site_20",
        "site_24",
        "site_25",
        "site_33"
      ]
    },
    {
      "id": "region_20",
      "name": "Boulderbrook",
      "resource": "stone",
      "capacity": 2,
      "path": "M751.1,880.7L678.3,735.2L709.2,671.4L821,635.6L931.9,707.2L931,724.7Z",
      "labelX": 793.5,
      "labelY": 741,
      "adjacentSiteIds": [
        "site_23",
        "site_27",
        "site_28",
        "site_29",
        "site_34"
      ]
    },
    {
      "id": "region_21",
      "name": "Sheaf Hollow",
      "resource": "grain",
      "capacity": 1,
      "path": "M1219.2,843.9L1201.5,852.2L1150,872.4L1095.8,889.7L1039.4,904.1L1025.9,906.7L931,724.7L931.9,707.2L1036.5,628.1L1151.1,654.6Z",
      "labelX": 1074.1,
      "labelY": 765.7,
      "adjacentSiteIds": [
        "site_22",
        "site_24",
        "site_28",
        "site_33",
        "site_36"
      ]
    },
    {
      "id": "region_22",
      "name": "Starwell Grove",
      "resource": "essence",
      "capacity": 1,
      "path": "M502.9,889.3L450,872.4L398.5,852.2L350,829.4L305,804.1L266,777.9L476.2,670.8L539.3,755.4Z",
      "labelX": 429.4,
      "labelY": 781.4,
      "adjacentSiteIds": [
        "site_26",
        "site_31",
        "site_32",
        "site_35"
      ]
    },
    {
      "id": "region_23",
      "name": "Honeydew Pastures",
      "resource": "grain",
      "capacity": 1,
      "path": "M746.6,928.6L739,928.4L678.4,923.5L618.8,915.3L560.6,904.1L504.2,889.7L502.9,889.3L539.3,755.4L678.3,735.2L751.1,880.7Z",
      "labelX": 629,
      "labelY": 837.8,
      "adjacentSiteIds": [
        "site_29",
        "site_31",
        "site_34",
        "site_35"
      ]
    },
    {
      "id": "region_24",
      "name": "Hartwood",
      "resource": "timber",
      "capacity": 1,
      "path": "M1025.9,906.7L981.2,915.3L921.6,923.5L861,928.4L800,930L746.6,928.6L751.1,880.7L931,724.7Z",
      "labelX": 889.2,
      "labelY": 855.7,
      "adjacentSiteIds": [
        "site_28",
        "site_34",
        "site_36"
      ]
    }
  ],
  "landmarks": [
    {
      "id": "royal_castle",
      "name": "Royal Castle",
      "siteId": "site_17"
    },
    {
      "id": "wizard_tower",
      "name": "Wizard Tower",
      "siteId": "site_16"
    },
    {
      "id": "adventurers_inn",
      "name": "Adventurers' Inn",
      "siteId": "site_09"
    },
    {
      "id": "dwarven_hall",
      "name": "Dwarven Hall",
      "siteId": "site_31"
    },
    {
      "id": "sacred_grove",
      "name": "Sacred Grove",
      "siteId": "site_02"
    }
  ],
  "menaceStarts": [
    {
      "menaceType": "toll_troll",
      "location": {
        "kind": "region",
        "regionId": "region_07"
      }
    },
    {
      "menaceType": "young_dragon",
      "location": {
        "kind": "region",
        "regionId": "region_21"
      }
    },
    {
      "menaceType": "bog_witch",
      "location": {
        "kind": "region",
        "regionId": "region_18"
      }
    },
    {
      "menaceType": "highwayman",
      "location": {
        "kind": "route",
        "routeId": "route_23"
      }
    },
    {
      "menaceType": "goblin_tinkers",
      "location": {
        "kind": "site",
        "siteId": "site_03"
      }
    }
  ],
  "questParams": {
    "kingsHighway": [
      "site_16",
      "site_02"
    ]
  }
};
